### ISSUE TITLE
Mobile View - "Solution by" label length

### ISSUE THREAD

**Issue by PopWarner** [pnp/m365-sample-gallery#27] opened 2021-05-19 21:50 UTC
The "Solutions submitted by..." label is running off the screen on mobile views. It causes the horizontal scroll seen in issue #26. 

![Sample-Gallery-Mobile-iPhoneXS-SolutionByLabel](https://user-images.githubusercontent.com/10676147/118889059-65b4c500-b8b1-11eb-9cbd-58f75ba01326.PNG)

**Comment by VesaJuvonen** [comment] 2021-06-08 08:01
@v-aaronbode  - reopening as as missing any conclusions if the issue is fixed or when it has been released. Let's be a bit more clear on the communications, so that both teams knows what is happening and that the work done for testing is properly appreciated... and acknowledged and fixes properly communicated.

When we fix something - please let us know if things were fixed, skipped and when it's available in the web site. Just typical open-source communication model on being respectful on the people spending time here.

**Comment by v-aaronbode** [comment] 2021-06-08 21:16
@VesaJuvonen - certainly, can do! I'll go through all of the closed items and make notes for clarity. 

This issue has been resolved and now properly adjusts the text in the viewport. This has been released on the prod environment.

<img width="487" alt="Screen Shot 2021-06-08 at 11 14 53 AM" src="https://user-images.githubusercontent.com/84800044/121258707-ef213c80-c84a-11eb-9d09-0dfad0a6109c.png">

**Closed by v-aaronbode** 2021-06-08 21:16 UTC
